Quick fix misleading message
Because "The second pivot is smaller than the first one ==> expected: <true> but was: <false>"  can be misleading it just says "The second pivot is smaller than the first one".